// <auto-generated />
namespace GemStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateItemAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateItemAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "202003061708398_CreateItemAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
